version: "3.7"
services:
  api-server:
    image: 'dncjf64/palette:latest'
    container_name: api-server
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    volumes:
      - ../../logs:/var/log/application-logs
    network_mode: host

# 참고
# profiles 별로 docker-compose 분리 시
# for the profile 'test'
#  docker-compose -f docker-compose-test.yml up

