spring:
  config:
    activate:
      on-profile: dev
    import: 'aws-parameterstore:'

aws:
  paramstore:
    enabled: true
    prefix: /config
    profile-separator: '-'
    name: app-palette
    fail-fast: false

kwc: ${mysql.url}
username: ${mysql.username}